(define(domain metricLight)
 (:requirements :strips :typing :fluents)
 (:types lamp garden)
 (:predicates (lamp ?l)
	          (garden ?g)
            (on ?l)
	           )
   (:functions
              (lamp-luminescence-level ?l)
              (requiredluminescencelevel ?g)
	            (presentluminescencelevel ?g)
              (total-no-lamp-used)
              (count))
 (:action switch-on-lamp
   :parameters (?g ?l)
   :precondition (and (lamp ?l)
		  (garden ?g)
		  (< (presentluminescencelevel ?g) (requiredluminescencelevel ?g))
      (not(on ?l))
		  )
   :effect (and
		 (increase (presentluminescencelevel ?g) (lamp-luminescence-level ?l))
     (decrease (lamp-luminescence-level ?l)(lamp-luminescence-level ?l))
     (increase (total-no-lamp-used)(count))
		 )
  )
  (:action switch-off-lamp
   :parameters (?g ?l)
   :precondition (and (lamp ?l)
		  (garden ?g)
		  (> (presentluminescencelevel ?g) (requiredluminescencelevel ?g))
      (on ?l))
   :effect (and
		 (decrease (presentluminescencelevel ?g) (lamp-luminescence-level ?l))
      (decrease (lamp-luminescence-level ?l)(lamp-luminescence-level ?l))
      (decrease (total-no-lamp-used)(count))
		 )
	)
)

